#! /usr/bin/python

import BaseHTTPServer

secret = ""

class handler(BaseHTTPServer.BaseHTTPRequestHandler):
    def do_GET(self):
        global secret
        self.send_response(200)
        self.end_headers()
        self.wfile.write(secret)

    def do_PUT(self):
        global secret
        len = int(self.headers.getheader('content-length', 0))
        secret = self.rfile.read(len)
        self.send_response(200)
        self.end_headers()

def escrow_server(port):
    BaseHTTPServer.HTTPServer(('', port), handler).serve_forever()

escrow_server(8888)
